version: '3'
services:
  directus:
    image: directus/directus:10:4:3
    ports:
      - 8055:8055
    volumes:
      - ./database:/directus/database
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
    environment:
      KEY: '255d861b-5ea1-5996-9aa3-922530ec40b1'
      SECRET: '6116487b-cda1-52c2-b5b5-c8022c45e263'
      ADMIN_EMAIL: 'admin@stacky.com'
      ADMIN_PASSWORD: 'test123'
      DB_CLIENT: 'sqlite3'
      DB_FILENAME: '/directus/database/data.db'
      FLOWS_EXEC_ALLOWED_MODULES: array:moment,uuid
